### ISSUE TITLE
autoprefixing for css

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#10]
This will ensure compatibility with more browsers, and keep our css clean

**Comment by NoctuaNivalis** [comment]
Plz fix, site it broke.

**Comment by werthen** [comment]
Autoprefixing takes a little while to compile. If you need autoprefixing for your browser, add it for yourself. We'll add autoprefixing in production when nanoc 4.4 comes out, which will support environments.
