### ISSUE TITLE
404 page broken

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/zeus.ugent.be#105]
- Normal links don't work: https://zeus.ugent.be/events/qsdqsdq or https://zeus.ugent.be/656
- The page itself works: https://zeus.ugent.be/404/

**Comment by wschella** [comment]
Getting the 404 on Chrome, Firefox and Edge (on Windows). Some weird cache issue?

**Comment by werthen** [comment]
This is an nginx config issue. Fixed in https://github.com/ZeusWPI/ansible-config/commit/cbcb272b9675b41e8870d76fe78b9e5893cd9c71
