### ISSUE TITLE
Tile overview

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#11]
An overview for all tiles that should be visible on the homepage.
These can be different sizes to feature important sections and should be nothing more than a distilation of information or an image/icon functioning as a link to the relevant page.

Some possible tilesizes (based on current 3 per row layout):
 - Full: full 3 column width
 - Wide: 2 column width
 - Standard: current tilesize
 - High: 2 row height
 - Small: 1/4 of current tilesize

Proposed tiles:
 - [x] Main event (full)
 - [x] Projects (standard)
 - [x] Events (standard)
 - [x] Gamification top 4 (wide)
 - [x] Some important projects (Hydra, 12urenloop, etc.) (all standard)
 - [x] Cammie (standard)
 - [x] Wiki (standard)
 - [x] Blogpost (high)
 - [x] Facebook, Github, RSS, ? (all small)
 - [ ] About Zeus (information, location, history(?), statuten, bestuur, verslagen, etc.) (all small)
 - [ ] Archives (small or standard)
 - [ ] Fotoloop (standard)
 - [x] Quote loop (wide or standard)
 
It would be fucking fantastic if these could be reorderd something something cookie, a man can only dream.

**Comment by feliciaan** [comment]
@wschella [web storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API)?

**Comment by wschella** [comment]
@feliciaan web storage for what?

**Comment by feliciaan** [comment]
@wschella for the setting storage, cookies are not that useful for a static site :)
