### ISSUE TITLE
i18n/Language consensus

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#118]
The site right now is a mix of dutch and english. Site pages are english, but content is dutch. We should convert everything to dutch, and afterwards maybe do some i18n

**Comment by wschella** [comment]
Do we want to convert project descriptions to Dutch? What about Pragmatic Programmer quotes?
I feel like content-language is not much of an issue, as English is well understood. 
But I agree we want some consistency in heading, tagging, meta-info, and the likes.

**Comment by werthen** [comment]
The quotes can stay the same, that isn't a problem, but the blog for example has "academic year" on the side, but all the content is dutch
