### ISSUE TITLE
Fill in metatags

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#12]
We want compatibility with

- [ ] Facebook (OpenGraph)
- [ ] Twitter
- [ ] Google (schema.org)

**Comment by werthen** [comment]
https://github.com/joshbuchea/HEAD

**Comment by werthen** [comment]
Slack uses a combination of these tags for their previews, look into this as well.

https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.g2fdzbk5n

**Comment by wschella** [comment]
I assume we want some set side-wide meta-tags, and let more content-specific tags be defined in blogpost/event files?
