### ISSUE TITLE
Improve events view

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#131]
These event previews aren't very pretty right now, could use a improvement.

**Comment by werthen** [comment]
@bhendric did this ❤️

**Comment by NoctuaNivalis** [comment]
Pretty, but please provide some upper margin on this title:
![2017-04-24-175504_494x109_escrotum](https://cloud.githubusercontent.com/assets/994166/25346167/2f2daa70-2917-11e7-915f-a05e407f60b1.png)

Also I'm not sure how feasible it would be to automatically darken and blur the images, in case someone creates whitish or horrible unreadable posters like these:
![2017-04-24-175712_677x534_escrotum](https://cloud.githubusercontent.com/assets/994166/25346294/80d6c230-2917-11e7-9109-3b8163cef335.png)

**Comment by wschella** [comment]
Autoblurring would be nice.

**Comment by werthen** [comment]
We'll have to do that with imagemagick im afraid, but it can be done

**Comment by NoctuaNivalis** [comment]
If you limit the blurring and darkening to the people who deserve it: CSS3 supports image filters?

**Comment by werthen** [comment]
That's true, but the live rendering can be really laggy :(

**Comment by wschella** [comment]
I feel like writing the full text on the home-page is not what we want, that's what we the description for.
This would certainly improve readability there, as it would allow us to enlarge the font significantly.

**Comment by werthen** [comment]
Absolutely right @wschella

**Comment by werthen** [comment]
Fixed, I'm quite glad with how @wschella fixed this
