### ISSUE TITLE
Search bar is misaligned with other icons

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#135]

**Comment by niknetniko** [comment]
Is it OK for the expanded search bar to have a gap?
![expanded](https://cloud.githubusercontent.com/assets/1756811/21195745/5ce3030a-c235-11e6-8999-d474771cfdaf.PNG)

**Comment by wschella** [comment]
Yes

**Comment by werthen** [comment]
yeah thats not a problem, as long as the icon is aligned
