### ISSUE TITLE
Allow multiple dates for a single event (e.g. FOSDEM)

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#139]

**Comment by wschella** [comment]
Isn't this what sub-events are for?

**Comment by werthen** [comment]
Hm, come to think of it, these types of events should just have an end date
a day later, sub events are something else entirely. I’ll close this in
favour for an "end date” issue.

Met vriendelijke groeten,
Lorin Werthen

Zeus WPI
Sysadmin ’16-’17
Event ’15-’16

From: Wout Schellaert <notifications@github.com> <notifications@github.com>
Reply: ZeusWPI/zeus.ugent.be
<reply@reply.github.com>
<reply@reply.github.com>
Date: 27 December 2016 at 13:54:14
To: ZeusWPI/zeus.ugent.be <zeus.ugent.be@noreply.github.com>
<zeus.ugent.be@noreply.github.com>
Cc: lorin <werthenlorin@gmail.com> <werthenlorin@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [ZeusWPI/zeus.ugent.be] Allow multiple dates for a single
event (e.g. FOSDEM) (#139)

Isn't this what sub-events are for?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZeusWPI/zeus.ugent.be/issues/139#issuecomment-269322349>,
or mute the thread
