### ISSUE TITLE
Use social media icons on About page

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#144]
Instead of a lot of ugly text, we could use social icons that are clear and visually guiding on the About page.
Possible examples Facebook, Twitter, etc...

**Comment by ubarsaiyan** [comment]
I will like to help but I am a newbie and don't know how to go about it. Can you help?

**Comment by werthen** [comment]
@ubarsaiyan is there any chance you could hop by the Zeus basement one of these days? I'd be happy to guide you into developing for this site a bit

**Comment by ubarsaiyan** [comment]
@werthen I'm sorry, there is no chance.

**Comment by werthen** [comment]
@ubarsaiyan Well, try and get [bundler](bundler.io) and [npm](npmjs.com) installed, then you can follow the brief installation instructions on the README

**Comment by werthen** [comment]
@wschella fixed this
