### ISSUE TITLE
Convert all previous event blogposts to event posts

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#171]
Tedious work, but could serve useful as an "archive". Necessary when #175 comes around.

**Comment by morrme** [comment]
What is involved in getting this done?

**Comment by werthen** [comment]
@morrme 

* Identifying which blogposts correspond with an event (such as https://github.com/ZeusWPI/zeus.ugent.be/blob/master/content/blog/15-16/geeks-attack-iv.md)
* Moving them to the corresponding folder in `content/events` (e.g `content/events/15-16`)
* Renaming/converting the metadata like in https://github.com/ZeusWPI/zeus.ugent.be/blob/master/content/events/16-17/LAN.md
