### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#174]
This repo really needs more documentation.

I take the blame on this one (for the most part).

Oops.

**Comment by wschella** [comment]
Agreed. Some key points:
 - There is a decent part about getting the project up and running, but it might be extended a bit, for example what the 'invisible' dependencies are. You need to install `npm` and `bundler`, which require `Node.js` and `Ruby` respectively, both of which are not just some light libraries to include, and could provide a whole bunch of trouble on their own. Some links might be useful.
 - It should be more clear from the readme that we use Nanoc.
 - A general layout/description might be useful, eg: we use this data from here, modify it there,  and display it over here automatically. Things that pop up are: events, blogs, navbar, etc...
 - For the Ruby/Nanoc novices, it could be nice to provide some pointers to key concepts that are used that rely on standardization and convention, as to be able to actually understand what is going on. For example: the helpers that are just called everywhere (without imports).
