### ISSUE TITLE
Create a timeline for the history page

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#177]
Key concepts:
 - Expandable timeline items (to handle large texts)
 - Splitting up in events, as to make more sense on a timeline, and provide smaller text

Another option might be to just provide an overview to the side.
Yet another option might be to use a horizontal timeline, allowing us to create larger bodies of text on the bottom.

**Comment by werthen** [comment]
https://wikiki.github.io/bulma-extensions/timeline

**Comment by werthen** [comment]
Fixed in #340
