### ISSUE TITLE
Deploy PR's to a staging server to preview site changes.

### ISSUE THREAD

**Issue by rien** [ZeusWPI/zeus.ugent.be#185]
This way, when a PR is submitted, the resulting site can be quickly checked before merging (blindly).

- [x] Comment on PR with link to preview
- [x] Update README with information about this

**Comment by wschella** [comment]
When the README is updated with how we use this feature, this issue can be closed. Implemented in #199

**Comment by werthen** [comment]
Partially implemented. This needs to be on king instead of my personal server (<pr>.zeus.werthen.com), and a comment should get placed on the PR with the URL of the PR preview.

**Comment by wschella** [comment]
With wildcard let's encrypt certificates, and [our own non-ugent site](zeuswpi.org), this is something we can host on Zeus servers now, and we should. A comment on the PR with the link and an update in the README would also be nice.

**Comment by werthen** [comment]
Already implemented on own servers, without wildcard certs (bit too big of a hassle it seems right now)

A comment on the PR with a link would be nice, same with the README. Updating issue to reflect this

**Comment by werthen** [comment]
Works with wildcard let's encrypt certs on *.pr.zeus.gent. Only thing that's really missing is a comment on the PR

**Comment by werthen** [comment]
Hello from GraphQL
