### ISSUE TITLE
Create internal structure

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/zeus.ugent.be#2]
- [x] how to group blogposts
- [ ] which files will be auto added to the header

Other things?

**Comment by werthen** [comment]
1. I think we'll best split up blogposts into event posts and normal posts. Both will have the `article` kind. Should we create a directory structure based on year and month? eg. `/2016/07`? maybe just year would be enough (would also reflect on which bestuur was active at that time)? We don't want to end up with a gigantic folder containing every single blogpost ever
2. What do you mean with "which files will be auto added to the header"?

**Comment by werthen** [comment]
This is a bit too general, closing this in favor for smaller issues
