### ISSUE TITLE
Upcoming events are ordered from late to upcoming

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#203]
This should be in reverse. Context: home page.

**Comment by membrq** [comment]
It looks like the events on the home page are already ordered from newest to oldest. Is there something else that needs to be changed?

**Comment by wschella** [comment]
Hello @membrq. You are correct ordering is fine for events _that already happened_, however when they are upcoming it'll show the event that will happen last first instead. Currently we have no events upcoming, so you can't quite see it on the live site. You could easily create test events, in the `content/events/17-18/` directory.

This mockup data will be ordered incorrectly:

```
---
title: Upcoming event!!
image: https://zeus.ugent.be/zeuswpi/HSmBFUWz.svg
description: Bezoek ons standje op Student Kick-Off
created_at: 23-09-2017
time: '01-01-2018 12:00'
end: '01-09-2018 17:30'
location: Student Village
banner: https://zeus.ugent.be/zeuswpi/rJG7R5S0.jpg
locationlink: Sint-Pietersplein, Gent
---

Ook deze Student Kick-Off staan we weer met een standje in de Student Village, kom ons bezoeken tussen 12u en 17u30!
```

```
---
title: Also upcoming but later
image: https://zeus.ugent.be/zeuswpi/HSmBFUWz.svg
description: Bezoek ons standje op Student Kick-Off
created_at: 23-09-2017
time: '27-09-2018 12:00'
end: '27-09-2018 17:30'
location: Student Village
banner: https://zeus.ugent.be/zeuswpi/rJG7R5S0.jpg
locationlink: Sint-Pietersplein, Gent
---

Ook deze Student Kick-Off staan we weer met een standje in de Student Village, kom ons bezoeken tussen 12u en 17u30!
```

Thanks for wanting to help!

**Comment by membrq** [comment]
Ah, ok! I understand. I'll work on this. :)

**Comment by werthen** [comment]
@redfast00 does #378 fix this?
