### ISSUE TITLE
Social icons don't display in firefox

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#209]
In the right part of the navbar, there are supposed to be some icons for Facebook, Twitter, GitHub, etc...

**Comment by wschella** [comment]
Nevermind, it's uBlock origin that blocks it, cause the icon's have a '.social-icon' class.

**Comment by werthen** [comment]
We can handle it by renaming it? The reason why an adblocker like mublock wants to block those icons is to prevent privacy issues. We are not using any of those badges or whatever on our page, so an adblocker shouldn't block it.

**Comment by wschella** [comment]
Agreed.

**Comment by redfast00** [comment]
Can't reproduce anymore, can this be closed?

**Comment by werthen** [comment]
Yeah I think I fixed this on the side some time
