### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#226]
I've had this thought myself before, and it was confirmed by @Miaoulo a couple of days ago. The current way the homepage is handled is not good. It's not immediately clear how it's structured, and gamification also needs clarification.

Instead of keeping this tiled design, I suggest we go to a sleek, more traditional list based design. Perhaps with large banners at the top for the next upcoming event?

**Comment by Miaoulo** [comment]
How about a minor design-themed codenight/brainstorming next week? Thursday evening?

**Comment by werthen** [comment]
Good idea, I'm up for that!
