### ISSUE TITLE
Update cammie controls to new basement layout

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#241]
Now we have a new layout in our basement, the controls for cammie need to be updated. We need to tweak the `set-x` and `set-y` values of the buttons.

**Comment by NoctuaNivalis** [comment]
I've just done this for my [sphere.sh](https://github.com/NoctuaNivalis/dotfiles/commit/1f9bdf30f69290cc8256953ff4c18eca34ece7b1), you can probably reuse those values.
