### ISSUE TITLE
Find more information on boards of the past

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#244]
Using the web archive we can find out a lot of information about ex-boardmembers. Even our wiki contains some information on old board-members, which we might want to save (for example when organising events with alumni)

**Comment by niknetniko** [comment]
[This link](https://www.ugent.be/nl/univgent/voorzieningen/collecties/archief/collectie/studenten/verenigingen/zeus.html) from #63 might be useful here as well, as it contains a list of all chairmen back to 1991.

**Comment by niknetniko** [comment]
Closed in #355.
