### ISSUE TITLE
Incorrect map is shown when not in Belgium (or near enough to Ghent?)

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/zeus.ugent.be#250]
I think it's just the `locationlink` on the events that are wrong? I just noticed the trend in a lot of events, so I thought I'd point it out.

**Comment by werthen** [comment]
Could you provide an example of a wrong map? I checked out all events of '17-'18 and they seem to be correct

**Comment by Procrat** [comment]
Sure.
https://zeus.ugent.be/events/17-18/lightning-talks/: UGent (St. Pietersnieuwstraat) instead of S9
https://zeus.ugent.be/events/17-18/zeus-kiest/: no location (maps shows whole world)
https://zeus.ugent.be/events/17-18/bottlebats-intro/: UGent (St. Pietersnieuwstraat) instead of S9
https://zeus.ugent.be/events/17-18/vpw/: idem
https://zeus.ugent.be/events/17-18/hashcode/: idem

**Comment by Miaoulo** [comment]
I checked as well and all seems fine here:
bottlebats: https://i.imgur.com/zgV0Cv1.png
Zeus kiest: https://i.imgur.com/2mllblp.png
Lightning talks: https://i.imgur.com/bNeisw5.png 

Is it possible that this breaks when outside of belgium? Maybe we should give more explicit locations

**Comment by Procrat** [comment]
![6xbvir](https://user-images.githubusercontent.com/607786/40608626-25440fac-62c0-11e8-84bc-4ce4eca54af9.png)
![vlv1ul](https://user-images.githubusercontent.com/607786/40608627-257a9a90-62c0-11e8-8dda-d2710a3cbbe7.png)

I'm guessing the `locationlink` metadata on the posts is used for these maps?
That would seem about right, because when I type in "Building S9 Universiteit Gent" in Google Maps (like for the [vpw event](https://raw.githubusercontent.com/ZeusWPI/zeus.ugent.be/master/content/events/17-18/vpw.md)), I see a marker on the rectorate, and when I type in "S9, Sterre" (like for [zeus kiest](https://raw.githubusercontent.com/ZeusWPI/zeus.ugent.be/master/content/events/17-18/zeus-kiest.md)), I see the whole world.

Edit: this actually changed o_o After doing a few UGent searches, "S9, Sterre" actually _does_ point to the right place. It'll probably be fine for students in Ghent, which is your main audience.

**Comment by wschella** [comment]
It probably has to do with locale and search history like you concluded yourself. Might be worthwhile to investigate in being a tad more specific in the locationlink anyway, as the only use for it is that very map.

**Comment by werthen** [comment]
Fixing #268 should fix this, as OSM is not sensitive to location context, and has unique identifiers for each location

**Comment by wschella** [comment]
Also OSM is way cooler.
