### ISSUE TITLE
Use a more privacy friendly alternative to Google Analytics

### ISSUE THREAD

**Issue by rien** [ZeusWPI/zeus.ugent.be#259]
For example https://usefathom.com/

**Comment by werthen** [comment]
The tracking code is present on the site, we only need to enable https for stats.zeus.gent, and deploy fathom on there

**Comment by werthen** [comment]
Fixed on server as well, using fathom right now

**Comment by wschella** [comment]
Should this be in the docs somewhere?

**Comment by werthen** [comment]
Documented in README
