### ISSUE TITLE
Fix styling of archive result pages

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#27]
- [ ] add date to preview
- [ ] sort posts from later to earlier (now alphabetically) 
- [ ] sort years from later to earlier (now alphabetically)
- [ ] add year overview show number of posts in each year

**Comment by feliciaan** [comment]
- [ ] add date to preview
- [ ] sort posts from later to earlier (now alphabetically) 
- [ ] sort years from later to earlier (now alphabetically)

**Comment by werthen** [comment]
not really relevant with current layout
