### ISSUE TITLE
Fix mobile view for about page board table

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#271]
![](https://i.imgur.com/Mvq5ZTj.jpg) this should be more accessible, with email links visible

**Comment by deezy136** [comment]
Can I work on this issue

**Comment by brickmaker17** [comment]
If you still need help with this I can Fork the repo and work on it.

**Comment by redfast00** [comment]
@brickmaker17 yup, we still need help with this, so feel free to fix this. URL is https://zeus.gent/about/about.

**Comment by brickmaker17** [comment]
Would this work? If so I will do a PR. 
![screen shot 2018-10-05 at 10 58 48 pm](https://user-images.githubusercontent.com/34072446/46567583-77105500-c8f2-11e8-8c4d-78f4abd24059.png)

**Comment by wschella** [comment]
Thanks!
