### ISSUE TITLE
Document pandoc and latex dependency

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#274]

**Comment by niknetniko** [comment]
Are they not documented?

> You will (momentarily) also need pandoc and latex to compile the reports from the board meetings. Refer to your OS package manager to install these things.

Or do you mean somewhere else? Or more prominently perhaps?

**Comment by wschella** [comment]
Oh, I guess i was looking at the prerequisites. It seems kind off hidden where it is now.

**Comment by werthen** [comment]
Documented in the prerequisites
