### ISSUE TITLE
Blog titles too large for box

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#286]
An example below

![](https://i.imgur.com/XTwgQg3.jpg) 

Should just be a slight adjustment to the css we have in place already.

**Comment by BalesabuGodugu** [comment]
i will work on this issue

**Comment by wschella** [comment]
Cool, if you need any help, let us know!

**Comment by BalesabuGodugu** [comment]
@wschella @werthen  tried to reproduce the issue. Not able to reproduce. tried  android and ios idevices.@werthen please let me know in which device you are facing this issue

**Comment by wschella** [comment]
@BalesabuGodugu i've checked too, and it only happens for me in chrome.
It's probably some browser thing for text splitting.

**Comment by wschella** [comment]
Might not be worth fixing unless you find something easy.
