### ISSUE TITLE
Christmas cat doesn't sit on the logo anymore :(

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#307]
![screenshot_2018-12-21 zeus wpi werkgroep informatica van de universiteit gent](https://user-images.githubusercontent.com/9478856/50330875-21187a00-04fd-11e9-9d4e-1f973e4595d9.png)

**Comment by wschella** [comment]
Or it was in front of the logo or smth, but this cannot stand!

**Comment by redfast00** [comment]
Fixed in https://github.com/ZeusWPI/zeus.ugent.be/commit/320f2d86caa74c292fc60179a939344dc47d55f1
