### ISSUE TITLE
About page redirect makes firefox angry

### ISSUE THREAD

**Issue by abeforgit** [ZeusWPI/zeus.ugent.be#330]
Firefox doesn't like automatic redirects/autorefresh anymore. When accessing the About page, a banner appears with "Firefox prevented this page from automatically redirecting to another page".

Sure, this warning can be turned off in about/config, but your average user won't do this. 
Worth checking if the redirect is absolutely necessary.

**Comment by redfast00** [comment]
@abeforgit I'm not able to reproduce this, can you please confirm this issue still exists/give the URL?

**Comment by werthen** [comment]
Also can't reproduce, closing for now

**Comment by abeforgit** [comment]
Sorry I didn't see the question. The url is https://zeus.ugent.be/about/
Which automatically tries to redirect to https://zeus.ugent.be/about/about
This happens consistently either by accessing the url directly or by clicking the "about" link in the navheader

Firefox version: 70.0b8 (developer edition)
