### ISSUE TITLE
Jobpage

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#350]
:dollar: :heavy_dollar_sign: :moneybag: 

Hou je bek maar over "integriteit"

**Comment by Robbe7730** [comment]
# integriteit

**Comment by ninewise** [comment]
'k Vind een jobpagina wel nog een goed idee. Ge kunt er dan op zetten dat Zeus daar niet aan mee doet en ze dus ook niet moeten mailen.

**Comment by timodw** [comment]
> 'k Vind een jobpagina wel nog een goed idee. Ge kunt er dan op zetten dat Zeus daar niet aan mee doet en ze dus ook niet moeten mailen.

Gewoon een redirect naar ceneka hun site

**Comment by niknetniko** [comment]
Closing as duplicate of #168.
