### ISSUE TITLE
Support grouped events

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#36]
We want to highlight multiple events in a blogpost, such as codenights. These kind of events are not so common though.

**Comment by wschella** [comment]
I'd say these events are the most common. But the blog posts not.
We might for example want to group BBB related events as well.

**Comment by werthen** [comment]
It might be a solution to keep the events seperate from the blogpost, and reference to them in the frontmatter of blogposts. For example

in `content/events/15-16/awk.md`
```markdown
---
title: Awk-les
time: 05-05-16
---
**Awesome** class
```

in `content/posts/15-16/awkpost1.md
```markdown
---
events:
  - 15-16/awk
---
This is a blogpost about the awk thing
``` 

This would create a clearer distinction between blogposts and events

**Comment by wschella** [comment]
I agree that making the disctinction would allow for more flexibility. And in our use case, it would certainly be used. For example, we want to create an event-page for every code night, but we might not want to write a blogpost each time. Or vice versa, announcing a new board requires a blogpost, but no event.

**Comment by werthen** [comment]
#40 discusses this further, is also already implemented a bit
