### ISSUE TITLE
Soleway use for location description

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#39]
I'd be cool if we could add a small description to reach The Kelder™ using Soleway or any other sufficient indoor routing platform (but since SW is UGent based and has significant Zeus input etc.).

Maybe even for events not happening at The Kelder™?

**Comment by werthen** [comment]
Is there an API available? Enlighten me

**Comment by feliciaan** [comment]
You can link to the route on the soleway site, for example: [Auditorium A3](https://soleway.ugent.be/routes/169). 

We should ask if they a "SoleWay"-button for the link.

**Comment by wschella** [comment]
Yes, but irrelevant. We could just link, like [this](https://soleway.ugent.be/routes/237) for example.

**Comment by werthen** [comment]
I guess we could map locations to those soleway links, might be interesting indeed

**Comment by wschella** [comment]
My main focus was for the Zeuskelder, as we could add a simple link on the contact/more-info/about page, which would be a trivial job.

If wanted, we could expand to frequently used rooms (as there are not so many we use), but that would be somewhat more complicated.

**Comment by werthen** [comment]
That's done in a jiffy, but it would be interesting to have soleway links for every location we use, as there are (as you said) not many. We could easily create a `locations.yml` that maps a location name to a soleway link, and simply use that data in our templates.

Would be fancy

**Comment by werthen** [comment]
Have been thinking about this, don't think it is as feasible as I thought it would be, as Soleway preferably has a "from" position as well. Closing for now.
