### ISSUE TITLE
Create file uploading service

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#4]
In order to keep the git repo small, we should only add plaintext posts here. Any images and other media should be served elsewhere. We should make a simple tool where you can upload files.

**Comment by Silox** [comment]
https://git-lfs.github.com/

2016-06-16 16:44 GMT+02:00 lorin <notifications@github.com>:

**Comment by werthen** [comment]
@Silox I thought about that, but we have no need for versioning these files, plus (as far as i understand it) people who clone this repo also pull in the latest version of what could be hundreds of images

**Comment by werthen** [comment]
This should also provide an interface (or automatically generate) smaller versions of images, so we can display those instead in certain places

**Comment by werthen** [comment]
https://github.com/zeuswpi/zeuswpi
