### ISSUE TITLE
Event structure

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#40]
## Events

Example structure:

```
content/
  assets/
  events/
    15-16/
    16-17/
      bottlebats/
        main.md
        intro.md
        codenight.md
        finale.md
      awk.md
      sed.md
      ruby.md
    index.erb
```

### Metadata

Every event is a `.md` file with the following metadata tags:

#### Required

* title: String
* time: Date
* location: String
* description: String

#### Optional

* banner: URL

### Grouped events

If there's a series of events (for example summer code nights) these can be grouped by creating a folder containing a `main.md`, which will need the following metadata:

#### Required

* title: String

#### Optional

* location: String
* banner: URL

Other `.md` files made in that folder are sub-events which need to fit the [metadata description listed earlier](###metadata)

**Comment by feliciaan** [comment]
So their will be a distinction between posts and events?
Posts are for random things like announcements or reviews and will have a folder, and an events-folder for events?

**Comment by werthen** [comment]
Yes, BUT that does not prevent us from making blogposts that refer to these events directly. This way you can still make multiple posts about an event (e.g. LAN-Party) and still keep the event as its own seperate thing

**Comment by werthen** [comment]
These events should also show up on the homescreen, so there will be a mix between blogposts and events on there.

**Comment by Miaoulo** [comment]
@werthen this is finished, right?

**Comment by werthen** [comment]
pretty much @Miaoulo, still some small issues with grouped events but we'll deal with those when we need to
