### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#45]
Tooltips.
Everywhere.

Or just where it makes sense.

**Comment by werthen** [comment]
where for example?

**Comment by wschella** [comment]
The icons in the header, the iconbased tiles.
The e-mail icon on the about page.

So, icons, mostly for when a user is not familiar with the icon meaning, or is not shure.
(Possible for: agenda, cammie, github, rss)

**Comment by werthen** [comment]
should we make tooltips for the tooltips?

**Comment by wschella** [comment]
Yes, recursively ad infinitum.

**Comment by werthen** [comment]
We should be able to fix everything without the need of tooltips honestly.
