### ISSUE TITLE
Author information

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#53]
We could add author information to every post. We usually just post in function of the entire board, but we might even accept blogposts from other members in the future on here, who knows.

**Comment by R13N** [comment]
Is it possible to keep track of when the blogpost was submitted and when it was last editted?

**Comment by R13N** [comment]
^ no?

**Comment by wschella** [comment]
@R13N I think meta-info like last-edited deserves it's separate issue.
This was only about identifying the author.

**Comment by R13N** [comment]
Ok then
