### ISSUE TITLE
Make titles on the homepage clickable

### ISSUE THREAD

**Issue by klaasg** [ZeusWPI/zeus.ugent.be#584]
The titles "Upcoming Events", "Past Events", "Top Coders" and "Blogposts" could be a link to the relevant page on the website.

**Comment by Harsh3363** [comment]
> The titles "Upcoming Events", "Past Events", "Top Coders" and "Blogposts" could be a link to the relevant page on the website.

Hi @klaasg below the titles the events are listed so I think there is no need to make those titles clickable unless all these events have a specific pages for each.

**Comment by Maahipal27** [comment]
Hi @klaasg please assign me this issue.

**Comment by FKD13** [comment]
@Maahipal27 We are hosting an event this evening so will leave this issue open for attendees.
