### ISSUE TITLE
Zeus' history page

### ISSUE THREAD

**Issue by Miaoulo** [ZeusWPI/zeus.ugent.be#63]
We should include a page which would be the equivalent of https://zeus.ugent.be/over-zeus-wpi/zeus-vroeger-nu/

Not sure if this should be on a different tab or if we should include this in a blogpost or in the "about" page

**Comment by Miaoulo** [comment]
we could also do a series of blogposts concerning this topic

**Comment by werthen** [comment]
we could probably put this in the about page if we reimagine that page just a tad

**Comment by werthen** [comment]
Bumping the priority again, This should get done soon.

**Comment by wschella** [comment]
[Relevant link.](https://www.ugent.be/nl/univgent/collecties/archief/collectie/studenten/verenigingen/zeus.html)

**Comment by werthen** [comment]
Fixed in 535fd231f5b9cb0374d4082130f81e537f608d35
