### ISSUE TITLE
Add all projects

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/zeus.ugent.be#79]

**Comment by wschella** [comment]
I don't agree that all projects should be featured.
Mainly things like userscripts, ansibleclient, oauth stuff have no place there.
But you are correct that some projects could be featured (Gamification for example).

**Comment by Procrat** [comment]
That is obviously what I meant.

**Comment by wschella** [comment]
Aha. Are there others then Gamification, and Blokmap you have your eye on?

**Comment by werthen** [comment]
closed by #87
