### ISSUE TITLE
Meeting reports, including PDF versions

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/zeus.ugent.be#99]
It would be cool to write reports in markdown, convert to PDF and have it centralised on the site

**Comment by feliciaan** [comment]
Pinging @iliclaey

**Comment by werthen** [comment]
@feliciaan I think she is on board

![https://cldup.com/Ju2aPX1Zvh.png](https://cldup.com/Ju2aPX1Zvh.png)

**Comment by werthen** [comment]
Bumping priority, reports should be generally available.
